name: Bug Report
description: Report a bug in Firefly Framework
labels: ["bug", "triage"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Affected Module
      description: Which module is affected?
      options:
        - core
        - domain
        - data
        - cqrs
        - eda
        - eventsourcing
        - transactional-engine
        - web
        - cache
        - r2dbc
        - client
        - application
        - backoffice
        - ecm
        - idp
        - notifications
        - plugins
        - rule-engine
        - webhooks
        - callbacks
        - workflow
        - config-server
        - validators
        - utils
        - bom
        - parent
        - genai
        - cli
        - other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Configure ...
        2. Call method ...
        3. Observe error ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened.
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Firefly Framework Version
      placeholder: "e.g. 26.02.02"
    validations:
      required: false

  - type: dropdown
    id: java-version
    attributes:
      label: Java Version
      options:
        - "25"
        - "24"
        - "23"
        - "22"
        - "21"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs / Stack Trace
      description: Paste any relevant log output or stack traces.
      render: shell
    validations:
      required: false
