name: Feature Request
description: Suggest a new feature or enhancement
labels: ["enhancement"]
body:
  - type: dropdown
    id: module
    attributes:
      label: Target Module
      description: Which module would this feature belong to?
      options:
        - core
        - domain
        - data
        - cqrs
        - eda
        - eventsourcing
        - orchestration
        - web
        - cache
        - r2dbc
        - client
        - application
        - backoffice
        - ecm
        - idp
        - notifications
        - plugins
        - rule-engine
        - webhooks
        - callbacks
        - config-server
        - validators
        - utils
        - bom
        - parent
        - genai
        - cli
        - other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this solve? What is the use case?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you would like.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples.
    validations:
      required: false
